// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface TrxRoot {
	TestRun: TestRun;
}

export interface TestRun {
	$: TestRunClass;
	Times: TimeElement[];
	TestSettings: TestSetting[];
	Results: Result[];
	TestDefinitions: TestDefinition[];
	TestEntries: TestRunTestEntry[];
	TestLists: TestRunTestList[];
	ResultSummary: ResultSummaryElement[];
}

export interface TestRunClass {
	id: string;
	name: string;
	runUser: string;
	xmlns: string;
}

export interface ResultSummaryElement {
	$: ResultSummary;
	Counters: Counter[];
}

export interface ResultSummary {
	outcome: string;
}

export interface Counter {
	$: { [key: string]: string };
}

export interface Result {
	UnitTestResult: UnitTestResult[];
}

export interface UnitTestResult {
	$: { [key: string]: string };
	Output: Output[];
}

export interface Output {
	StdOut: string[];
	ErrorInfo: ErrorInfo[];
}

export interface ErrorInfo {
	Message: string[];
	StackTrace: string[];
}

export interface TestDefinition {
	UnitTest: UnitTestElement[];
}

export interface UnitTestElement {
	$: UnitTest;
	Execution: ExecutionElement[];
	TestMethod: TestMethodElement[];
}

export interface UnitTest {
	name: string;
	storage: string;
	id: string;
}

export interface ExecutionElement {
	$: Execution;
}

export interface Execution {
	id: string;
}

export interface TestMethodElement {
	$: TestMethod;
}

export interface TestMethod {
	codeBase: string;
	adapterTypeName: string;
	className: string;
	name: string;
}

export interface TestRunTestEntry {
	TestEntry: TestEntryTestEntry[];
}

export interface TestEntryTestEntry {
	$: TestEntry;
}

export interface TestEntry {
	testId: string;
	executionId: string;
	testListId: string;
}

export interface TestRunTestList {
	TestList: TestListTestList[];
}

export interface TestListTestList {
	$: TestList;
}

export interface TestList {
	name: string;
	id: string;
}

export interface TestSetting {
	$: TestList;
	Deployment: DeploymentElement[];
}

export interface DeploymentElement {
	$: Deployment;
}

export interface Deployment {
	runDeploymentRoot: string;
}

export interface TimeElement {
	$: Time;
}

export interface Time {
	creation: string;
	queuing: string;
	start: string;
	finish: string;
}
